---
title: "Parallel computing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
Big data requires a lot of computing. Computer clusters and video cards can perform many calculations in parallel. But that requires that your computing task actually allows data to be processed in parallel. In this assignment you will use Nextflow to calculate LogP values for molecules encoded as SMILES that you retrieved from Wikidata. See the [GitHub repository](https://github.com/Rrtk2/MSB1015-Assignment-3) for more details.


## Programming language
 - Linux
 - Nextflow


## Programming apporaches
 - WikiData query 
 - Chemistry Development Kit (cdk)


##### Workflow
The following workflow is applied:

1) Data extraction from WikiData.

2) Data parsing using [the Chemistry Development Kit](https://cdk.github.io/cdk/) in Nextflow.

3) Extract logP value for every SMILES (around 150,000).

4) Re-run the steps 1, 2 and 3 with 1, 2 and 4 cores.

5) Compare running times.


#### Script block 1: Title

```{}
	text
```



